[package]
name = "frontend"
version = "0.2.0-beta.a"
edition = "2024"
repository = "https://github.com/BERADQ/vrc-stt-rs"

[dependencies]
anyhow.workspace = true
chrono = "0.4"
common.workspace = true
eframe = "0.33.3"
env_logger.workspace = true
log.workspace = true
rust-i18n.workspace = true
serde.workspace = true
serde_json.workspace = true
uds_windows.workspace = true

[features]
cuda = []
