[package]
name = "backend"
version = "0.2.0-beta.a"
edition = "2024"
repository = "https://github.com/BERADQ/vrc-stt-rs"

[dependencies]
anyhow.workspace = true
arrayvec = "0.7"
audioadapter-buffers = "2.0.0"
common.workspace = true
cpal = "0.17.1"
ctrlc = "3.4"
env_logger.workspace = true
log.workspace = true
rosc = "0.11.4"
rubato = "1.0.1"
rust-i18n.workspace = true
serde.workspace = true
serde_json.workspace = true
uds_windows.workspace = true
webrtc-vad = "0.4.0"
whisper-rs = { version = "0.15.1", features = ["cuda"] }

[features]
default = ["vulkan"]
cuda = ["whisper-rs/cuda"]
intel-sycl = ["whisper-rs/intel-sycl"]
openblas = ["whisper-rs/openblas"]
vulkan = ["whisper-rs/vulkan"]
